version: '3.7'

services:
  user_service:
    build: ./user_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./user_service/:/app/
    ports:
      - 8001:8000
    restart: always
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
      # - VENDOR_SERVICE_HOST_URL=http://vendor_service:8000/api/v1/vendors/
      # - CAT_SERVICE_HOST_URL=http://categories_service:8000/api/v1/categories/
      - WAIT_HOSTS=user_db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - user_db


  user_db:
    image: postgres:15-alpine
    volumes:
      - ./databases/postgres_data_user/:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    restart: always  
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service


  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080" 

# volumes:
#   databases:
#   postgres_data_products:
#   postgres_data_user:
#   postgres_data_client:
#   postgres_data_vendor:
