version: '3.7'

services:
  user_service:
    build: ./user_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./user_service/:/app/
    ports:
      - 8001:8000
    restart: always
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
      # - VENDOR_SERVICE_HOST_URL=http://vendor_service:8000/api/v1/vendors/
      # - CAT_SERVICE_HOST_URL=http://categories_service:8000/api/v1/categories/
      - WAIT_HOSTS=user_db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - user_db

  product_service:
    build: ./product_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./product_service/:/app/
    ports:
      - 8002:8000
    restart: always
    environment:
      - PRODUCT_DATABASE_URI=postgresql://product_db_username:product_db_password@product_db/product_db_dev
      # - VENDOR_SERVICE_HOST_URL=http://vendor_service:8000/api/v1/vendors/
      # - CAT_SERVICE_HOST_URL=http://categories_service:8000/api/v1/categories/
      - WAIT_HOSTS=product_db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - product_db



  inventory_service:
    build: ./inventory_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./inventory_service/:/app/
    ports:
      - 8003:8000
    restart: always
    environment:
      - INVENTORY_DATABASE_URI=postgresql://inventory_db_username:inventory_db_password@inventory_db/inventory_db_dev
      # - VENDOR_SERVICE_HOST_URL=http://vendor_service:8000/api/v1/vendors/
      # - CAT_SERVICE_HOST_URL=http://categories_service:8000/api/v1/categories/
      - WAIT_HOSTS=product_db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - inventory_db





  order_management_service:
    build: ./order_management_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./order_management_service/:/app/
    ports:
      - 8004:8000
    restart: always
    environment:
      - OMS_DATABASE_URI=postgresql://order_management_db_username:order_management_db_password@order_mangement_db/order_management_db_dev
      # - VENDOR_SERVICE_HOST_URL=http://vendor_service:8000/api/v1/vendors/
      # - CAT_SERVICE_HOST_URL=http://categories_service:8000/api/v1/categories/
      - WAIT_HOSTS=product_db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - order_mangement_db



  gatway_service:
    build: ./gatway_service
    command: sh -c "/wait && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./gatway_service/:/app/
    ports:
      - 8005:8000
    restart: always


  user_db:
    image: postgres:15-alpine
    volumes:
      - ./databases/postgres_data_user/:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev

  product_db:
      image: postgres:15-alpine
      volumes:
        - ./databases/postgres_data_product/:/var/lib/postgresql/data/
      restart: always
      environment:
        - POSTGRES_USER=product_db_username
        - POSTGRES_PASSWORD=product_db_password
        - POSTGRES_DB=product_db_dev


  inventory_db:
      image: postgres:15-alpine
      volumes:
        - ./databases/postgres_data_inventory/:/var/lib/postgresql/data/
      restart: always
      environment:
        - POSTGRES_USER=inventory_db_username
        - POSTGRES_PASSWORD=inventory_db_password
        - POSTGRES_DB=inventory_db_dev


  order_mangement_db:
      image: postgres:15-alpine
      volumes:
        - ./databases/postgres_data_order_management/:/var/lib/postgresql/data/
      restart: always
      environment:
        - POSTGRES_USER=order_management_db_username
        - POSTGRES_PASSWORD=order_management_db_password
        - POSTGRES_DB=order_management_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    restart: always  
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service


  nginx_main:
     image: nginx:latest
     ports:
      - "80:80"
     restart: always  
     volumes:
  
       - ./dist:/usr/share/nginx/html


  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080" 

# volumes:
#   databases:
#   postgres_data_products:
#   postgres_data_user:
#   postgres_data_client:
#   postgres_data_vendor:
