"""create categorys table from CategoryModel model

Revision ID: 26056d723916
Revises: 
Create Date: 2023-04-25 12:12:02.983638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26056d723916'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
     pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('units',
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('en_title', sa.String(length=50), nullable=True),
    # sa.Column('ar_title', sa.String(length=50), nullable=True),
    # sa.Column('ShortName', sa.String(length=50), nullable=True),
    # sa.Column('base_unit', sa.Integer(), nullable=True),
    # sa.Column('operator', sa.String(length=192), nullable=True),
    # sa.Column('operator_value', sa.Float(precision=10), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_units_base_unit'), 'units', ['base_unit'], unique=False)
    # op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_base_unit'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
